"""Build a supervised fine-tuning corpus for the risk-answer interpreter.

The corpus teaches one narrow task: given a framework question and a bounded set
of raw source evidence, choose one controlled answer, cite the supplied evidence
that supports it, and abstain when the evidence does not establish an answer.

Three properties make the corpus worth training on, and each is enforced here
rather than left to the caller.

Prompts are generated by the same functions that build inference prompts
(``question_evidence``/``_question_prompt``) over the same sanitized evidence
view that ``review_answers_with_ai`` uses. A corpus whose prompts differ in
shape from production prompts trains the model for a task it will never be
asked to perform, so the private inference helpers are imported deliberately:
they are the single source of truth, and ``test_training_corpus`` asserts the
generated prompt equals what the inference path would send.

Labels come from NARA, and NARA evidence is also present in the registry. If a
model is shown NARA's answer and asked to predict NARA's answer it learns to
copy a field, and the resulting accuracy measures transcription. Tiering
controls that exposure: Tier A removes NARA evidence entirely, Tier B removes
only NARA's answer to the question being asked, and Tier C removes evidence
altogether to teach abstention. Only Tier A is used for evaluation.

Abstention is a first-class label. A model trained only on answerable questions
stops abstaining, and an accuracy metric computed over well-evidenced formats
will not show it.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from dataclasses import dataclass, field
import json
from pathlib import Path
import random
from typing import Any, Iterator

from preservation_risk_manager.ai.review import raw_review_evidence_pack
from preservation_risk_manager.ai.risk_analysis import (
    RISK_INTERPRETER_SYSTEM_PROMPT,
    _claim_matches_question,
    _question_prompt,
    question_evidence,
)
from preservation_risk_manager.answer_derivation import derive_answers
from preservation_risk_manager.data_access import RegistryReader
from preservation_risk_manager.errors import PreservationRiskManagerError
from preservation_risk_manager.evidence_packs import build_evidence_pack
from preservation_risk_manager.frameworks import Question, RiskFramework


TIER_A = "A"
TIER_B = "B"
TIER_C = "C"
VALID_TIERS = (TIER_A, TIER_B, TIER_C)

SPLIT_TRAIN = "train"
SPLIT_VAL = "val"
SPLIT_TEST = "test"
SPLITS = (SPLIT_TRAIN, SPLIT_VAL, SPLIT_TEST)

NARA_SOURCE_PREFIX = "nara"
LABEL_SOURCE = "nara_rubric"

ABSTENTION_NO_EVIDENCE = "no_evidence"
ABSTENTION_INCONCLUSIVE = "inconclusive"

# Only unambiguous deterministic derivations become labels. A
# ``derived_conflict_conservative`` result is the framework's tie-break rule
# applied to disagreeing sources, not a reading of the evidence, so training on
# it would teach the tie-break instead of the interpretation.
LABEL_STATUS = "derived"


class TrainingCorpusError(PreservationRiskManagerError):
    """Raised when a training corpus cannot be built or fails its quality gates."""


@dataclass(frozen=True)
class CorpusSettings:
    """Controls corpus construction, splitting, and the build's quality gates."""

    corpus_version: str
    tiers: tuple[str, ...] = VALID_TIERS
    abstention_share: float = 0.12
    abstention_tolerance: float = 0.03
    split_seed: int = 20260901
    test_share: float = 0.15
    val_share: float = 0.10
    max_evidence_items: int = 20
    min_test_examples_per_question: int = 30
    max_answer_share: float = 0.90
    institution_id: str | None = None
    max_formats: int | None = None

    def __post_init__(self) -> None:
        unknown = [tier for tier in self.tiers if tier not in VALID_TIERS]
        if unknown:
            raise TrainingCorpusError(
                f"Unknown corpus tier(s): {', '.join(unknown)}. Allowed tiers: {', '.join(VALID_TIERS)}"
            )
        if not self.tiers:
            raise TrainingCorpusError("At least one corpus tier must be selected.")
        if not 0 <= self.abstention_share < 1:
            raise TrainingCorpusError("abstention_share must be between 0 and 1.")
        if not 0 < self.test_share < 1 or not 0 <= self.val_share < 1:
            raise TrainingCorpusError("test_share must be in (0,1) and val_share in [0,1).")
        if self.test_share + self.val_share >= 1:
            raise TrainingCorpusError("test_share + val_share must leave a non-empty train split.")


@dataclass
class Example:
    """One (format, question) training example plus its non-model metadata."""

    prompt: str
    target: dict[str, Any]
    meta: dict[str, Any]
    referenced_refs: tuple[str, ...] = ()
    input_source_ids: tuple[str, ...] = ()

    def to_record(self) -> dict[str, Any]:
        return {
            "messages": [
                {"role": "system", "content": RISK_INTERPRETER_SYSTEM_PROMPT},
                {"role": "user", "content": self.prompt},
                {"role": "assistant", "content": json.dumps(self.target, sort_keys=True)},
            ],
            "meta": self.meta,
        }


def is_nara_claim(claim: dict[str, Any]) -> bool:
    """Return True when a claim originates from the NARA framework used for labels."""
    for key in ("source_id", "source_type"):
        if str(claim.get(key) or "").strip().lower().startswith(NARA_SOURCE_PREFIX):
            return True
    return False


def build_input_evidence(
    claims: list[dict[str, Any]],
    question: Question,
    tier: str,
) -> list[dict[str, Any]]:
    """Return the claims allowed into the model input for one tier.

    Tier A withholds every NARA claim, so a Tier A input cannot contain the
    source the label came from. Tier B withholds only NARA's answer to *this*
    question and keeps NARA's answers to the others: correlated leakage remains
    (a rubric score for one criterion predicts another), which is why Tier B is
    training-only. Tier C supplies nothing.
    """
    if tier == TIER_A:
        return [claim for claim in claims if not is_nara_claim(claim)]
    if tier == TIER_B:
        return [
            claim
            for claim in claims
            if not (is_nara_claim(claim) and _claim_matches_question(claim, question))
        ]
    if tier == TIER_C:
        return []
    raise TrainingCorpusError(f"Unknown corpus tier: {tier}")


def _format_id(format_doc: dict[str, Any]) -> str:
    return str(
        format_doc.get("canonical_id")
        or format_doc.get("format_id")
        or format_doc.get("id")
        or ""
    )


def _sources_of(claims: list[dict[str, Any]]) -> tuple[str, ...]:
    return tuple(sorted({str(claim.get("source_id") or "") for claim in claims if claim.get("source_id")}))


def _confidence_for(cited: list[dict[str, Any]]) -> float:
    """Return a deterministic confidence prior for a labelled example.

    This is a *prior*, not a measured calibration: the corpus has no ground
    truth for how certain a reading should be. It rewards corroboration across
    independent sources and directly asserted claims over derived ones, so the
    model learns to vary confidence with evidence strength rather than emitting
    a constant. Recalibrate against held-out agreement after training.
    """
    if not cited:
        return 0.0
    sources = {str(item.get("source_id") or "") for item in cited}
    asserted = any(str(item.get("directness") or "").lower() == "asserted" for item in cited)
    confidence = 0.70
    confidence += 0.10 * min(len(sources) - 1, 2)
    if asserted:
        confidence += 0.10
    return round(min(confidence, 0.95), 2)


def _rationale_for(question: Question, answer_id: str, cited: list[dict[str, Any]]) -> str:
    """Return a grounded rationale built only from the cited evidence.

    Every clause is derived from a field that is present in the model input, so
    the corpus never teaches the model to justify an answer with facts it was
    not shown.
    """
    parts: list[str] = []
    for item in cited[:3]:
        source = str(item.get("source_id") or "supplied evidence")
        field_name = str(item.get("source_field") or item.get("criterion_id") or "")
        value = str(item.get("source_value") or item.get("value") or "")
        fragment = f"{source} reports"
        if field_name:
            fragment += f" '{field_name}'"
        if value:
            fragment += f" as '{value}'"
        parts.append(fragment)
    if not parts:
        return f"Supplied evidence supports the controlled answer '{answer_id}'."
    joined = "; ".join(parts)
    return (
        f"{joined}. Taken together the supplied evidence addresses "
        f"'{'/'.join(question.evidence_fields) or question.id}' and supports the controlled "
        f"answer '{answer_id}'."
    )


def _abstention_answer(question: Question, framework: RiskFramework):
    answer = question.unknown_answer(framework.unknown_answer_id)
    if answer is None:
        raise TrainingCorpusError(
            f"Question {question.id} defines no abstention answer, so abstention examples cannot be built."
        )
    return answer


def _build_prompt(
    framework: RiskFramework,
    question: Question,
    claims: list[dict[str, Any]],
    format_doc: dict[str, Any],
    settings: CorpusSettings,
) -> tuple[str, list[dict[str, Any]], dict[str, Any]]:
    """Return (prompt, referenced_evidence, sanitized_pack) exactly as review-all would."""
    pack = build_evidence_pack(
        format_doc,
        institution_id=settings.institution_id,
        criterion_claims=claims,
    )
    review_pack = raw_review_evidence_pack(pack)
    deterministic_result = derive_answers(framework, review_pack)["derivation"][question.id]
    referenced = question_evidence(
        question,
        review_pack,
        deterministic_result,
        max_items=settings.max_evidence_items,
        prefer_deterministic_evidence=False,
    )
    prompt = _question_prompt(
        framework,
        question,
        review_pack,
        deterministic_result,
        referenced,
        include_deterministic_context=False,
    )
    return prompt, referenced, review_pack


def _meta(
    format_doc: dict[str, Any],
    question: Question,
    framework: RiskFramework,
    tier: str,
    settings: CorpusSettings,
    **extra: Any,
) -> dict[str, Any]:
    meta = {
        "canonical_id": _format_id(format_doc),
        "question_id": question.id,
        "criterion": list(question.evidence_fields),
        "label_source": LABEL_SOURCE,
        "tier": tier,
        "framework_id": framework.framework_id,
        "framework_version": framework.version,
        "corpus_version": settings.corpus_version,
    }
    meta.update(extra)
    return meta


def _labelled_example(
    framework: RiskFramework,
    question: Question,
    format_doc: dict[str, Any],
    all_claims: list[dict[str, Any]],
    label: dict[str, Any],
    tier: str,
    settings: CorpusSettings,
) -> Example | None:
    """Build one answerable example, or None when it would teach a bad habit."""
    input_claims = build_input_evidence(all_claims, question, tier)
    if not input_claims:
        return None
    prompt, referenced, _ = _build_prompt(framework, question, input_claims, format_doc, settings)
    if not referenced:
        return None

    # The label came from NARA, which tier filtering removed from the input. The
    # example may only cite evidence the model can actually see, so the citation
    # is the surviving evidence that addresses this question's criterion. With
    # none, a non-abstention answer would be uncitable and the example would
    # teach the model to answer from evidence it was never shown.
    supporting = [
        entry for entry in referenced if _claim_matches_question(entry["evidence"], question)
    ]
    if not supporting:
        return None

    cited = [entry["evidence"] for entry in supporting]
    answer_id = str(label["answer_id"])
    target = {
        "question_id": question.id,
        "answer_id": answer_id,
        "confidence": _confidence_for(cited),
        "rationale": _rationale_for(question, answer_id, cited),
        "evidence_refs": [entry["ref"] for entry in supporting],
        "uncertainty": "",
    }
    meta = _meta(
        format_doc,
        question,
        framework,
        tier,
        settings,
        answer_id=answer_id,
        label_status=str(label.get("status") or ""),
        label_sources=list(_sources_of(label.get("evidence_claims") or [])),
        input_sources=list(_sources_of(cited)),
        citations=[
            {
                "source_id": item.get("source_id"),
                "field": item.get("source_field") or item.get("criterion_id"),
                "value": item.get("source_value") or item.get("value"),
            }
            for item in cited
        ],
        abstention=False,
    )
    return Example(
        prompt=prompt,
        target=target,
        meta=meta,
        referenced_refs=tuple(entry["ref"] for entry in referenced),
        input_source_ids=_sources_of([entry["evidence"] for entry in referenced]),
    )


def _abstention_example(
    framework: RiskFramework,
    question: Question,
    format_doc: dict[str, Any],
    all_claims: list[dict[str, Any]],
    variant: str,
    settings: CorpusSettings,
) -> Example | None:
    """Build a Tier C example whose correct answer is the framework's abstention."""
    answer = _abstention_answer(question, framework)
    if variant == ABSTENTION_NO_EVIDENCE:
        input_claims: list[dict[str, Any]] = []
    else:
        # Evidence is present but none of it addresses this criterion, so the
        # correct behaviour is to abstain despite having something to read.
        input_claims = [
            claim for claim in all_claims if not _claim_matches_question(claim, question)
        ]
        if not input_claims:
            return None

    prompt, referenced, _ = _build_prompt(framework, question, input_claims, format_doc, settings)
    if variant == ABSTENTION_NO_EVIDENCE and referenced:
        return None
    if variant == ABSTENTION_INCONCLUSIVE:
        if not referenced:
            return None
        if any(_claim_matches_question(entry["evidence"], question) for entry in referenced):
            return None

    reason = (
        "No supplied evidence addresses this criterion."
        if variant == ABSTENTION_NO_EVIDENCE
        else "Supplied evidence does not address this criterion and cannot establish an answer."
    )
    target = {
        "question_id": question.id,
        "answer_id": answer.id,
        "confidence": 0.0,
        "rationale": reason,
        "evidence_refs": [],
        "uncertainty": reason,
    }
    meta = _meta(
        format_doc,
        question,
        framework,
        TIER_C,
        settings,
        answer_id=answer.id,
        abstention=True,
        abstention_reason=variant,
        input_sources=list(_sources_of([entry["evidence"] for entry in referenced])),
        citations=[],
    )
    return Example(
        prompt=prompt,
        target=target,
        meta=meta,
        referenced_refs=tuple(entry["ref"] for entry in referenced),
        input_source_ids=_sources_of([entry["evidence"] for entry in referenced]),
    )


def _nara_labels(
    framework: RiskFramework,
    format_doc: dict[str, Any],
    claims: list[dict[str, Any]],
    settings: CorpusSettings,
) -> dict[str, dict[str, Any]]:
    """Return NARA-derived labels per question, keeping only clean derivations."""
    nara_claims = [claim for claim in claims if is_nara_claim(claim)]
    if not nara_claims:
        return {}
    pack = build_evidence_pack(
        format_doc,
        institution_id=settings.institution_id,
        criterion_claims=nara_claims,
    )
    derivation = derive_answers(framework, pack)["derivation"]
    return {
        question_id: result
        for question_id, result in derivation.items()
        if str(result.get("status") or "") == LABEL_STATUS
    }


def generate_examples(
    reader: RegistryReader,
    framework: RiskFramework,
    settings: CorpusSettings,
) -> tuple[list[Example], dict[str, Any]]:
    """Generate every answerable (Tier A/B) example, with construction counters."""
    formats = sorted(reader.list_canonical_formats(), key=_format_id)
    if settings.max_formats is not None:
        formats = formats[: settings.max_formats]

    examples: list[Example] = []
    stats: Counter[str] = Counter()
    stats["formats_scanned"] = len(formats)

    answerable_tiers = [tier for tier in settings.tiers if tier in (TIER_A, TIER_B)]
    for format_doc in formats:
        if not _format_id(format_doc):
            stats["formats_without_id"] += 1
            continue
        claims = reader.get_criterion_claims_for_format(
            format_doc,
            institution_id=settings.institution_id,
        )
        if not claims:
            stats["formats_without_claims"] += 1
            continue
        labels = _nara_labels(framework, format_doc, claims, settings)
        if not labels:
            stats["formats_without_nara_label"] += 1
            continue
        stats["formats_with_labels"] += 1
        for question in framework.questions:
            label = labels.get(question.id)
            if label is None:
                continue
            stats["labelled_pairs"] += 1
            built: dict[str, Example] = {}
            for tier in answerable_tiers:
                example = _labelled_example(
                    framework, question, format_doc, claims, label, tier, settings
                )
                if example is None:
                    stats[f"tier_{tier}_rejected"] += 1
                    continue
                # Tier B only earns a place when withholding NARA's answer to
                # this question actually leaves different evidence than Tier A.
                # When a format's only relevant NARA claim is the one being
                # withheld, both tiers produce the same input, and keeping both
                # would double-weight that format for no additional signal.
                if tier == TIER_B and TIER_A in built and built[TIER_A].prompt == example.prompt:
                    stats["tier_B_duplicate_of_tier_a"] += 1
                    continue
                stats[f"tier_{tier}_built"] += 1
                built[tier] = example
                examples.append(example)
    return examples, dict(stats)


def generate_abstention_examples(
    reader: RegistryReader,
    framework: RiskFramework,
    settings: CorpusSettings,
    target_count: int,
    *,
    exclude_formats: set[str] | None = None,
) -> list[Example]:
    """Build Tier C examples across a deterministic sample of (format, question) pairs.

    ``exclude_formats`` keeps abstention examples off the evaluation formats.
    Tier C is training-only — evaluation runs on held-out Tier A — so building
    them for a held-out format would only discard them again after splitting,
    and would silently pull the corpus below its abstention target.
    """
    if target_count <= 0 or TIER_C not in settings.tiers:
        return []
    formats = sorted(reader.list_canonical_formats(), key=_format_id)
    if settings.max_formats is not None:
        formats = formats[: settings.max_formats]
    excluded = exclude_formats or set()
    formats = [doc for doc in formats if _format_id(doc) and _format_id(doc) not in excluded]
    if not formats:
        return []

    pairs = [(doc, question) for doc in formats for question in framework.questions]
    rng = random.Random(settings.split_seed)
    rng.shuffle(pairs)

    examples: list[Example] = []
    claim_cache: dict[str, list[dict[str, Any]]] = {}
    for index, (format_doc, question) in enumerate(pairs):
        if len(examples) >= target_count:
            break
        canonical_id = _format_id(format_doc)
        if canonical_id not in claim_cache:
            claim_cache[canonical_id] = reader.get_criterion_claims_for_format(
                format_doc,
                institution_id=settings.institution_id,
            )
        variant = ABSTENTION_NO_EVIDENCE if index % 2 == 0 else ABSTENTION_INCONCLUSIVE
        example = _abstention_example(
            framework, question, format_doc, claim_cache[canonical_id], variant, settings
        )
        if example is None:
            continue
        examples.append(example)
    return examples


def split_formats(
    format_ids: list[str],
    settings: CorpusSettings,
) -> dict[str, set[str]]:
    """Partition formats — never rows — across splits.

    Two questions about the same format share that format's evidence and
    identity, so splitting by row would place correlated examples on both sides
    of the evaluation boundary.
    """
    ordered = sorted(set(format_ids))
    rng = random.Random(settings.split_seed)
    rng.shuffle(ordered)
    total = len(ordered)
    test_count = int(settings.test_share * total)
    val_count = int(settings.val_share * total)
    return {
        SPLIT_TEST: set(ordered[:test_count]),
        SPLIT_VAL: set(ordered[test_count : test_count + val_count]),
        SPLIT_TRAIN: set(ordered[test_count + val_count :]),
    }


def assign_splits(
    examples: list[Example],
    settings: CorpusSettings,
    *,
    membership: dict[str, set[str]] | None = None,
) -> tuple[dict[str, list[Example]], dict[str, Any]]:
    """Route examples to splits, keeping evaluation to held-out Tier A only.

    Tier B and Tier C examples for an evaluation format are discarded rather
    than moved to train: moving them would put the same format on both sides of
    the split, which is the leak the split exists to prevent.
    """
    if membership is None:
        format_ids = [str(example.meta["canonical_id"]) for example in examples]
        membership = split_formats(format_ids, settings)
    splits: dict[str, list[Example]] = {name: [] for name in SPLITS}
    dropped = Counter()

    for example in examples:
        canonical_id = str(example.meta["canonical_id"])
        tier = str(example.meta["tier"])
        if canonical_id in membership[SPLIT_TEST]:
            if tier != TIER_A:
                dropped[f"test_format_non_tier_a_{tier}"] += 1
                continue
            splits[SPLIT_TEST].append(example)
        elif canonical_id in membership[SPLIT_VAL]:
            if tier != TIER_A:
                dropped[f"val_format_non_tier_a_{tier}"] += 1
                continue
            splits[SPLIT_VAL].append(example)
        else:
            splits[SPLIT_TRAIN].append(example)

    for name in SPLITS:
        splits[name].sort(key=lambda item: (item.meta["canonical_id"], item.meta["question_id"], item.meta["tier"]))
    info = {
        "formats_per_split": {name: len(membership[name]) for name in SPLITS},
        "dropped_examples": dict(dropped),
        "eval_tier": TIER_A,
    }
    return splits, info


def _answer_distribution(examples: list[Example]) -> dict[str, dict[str, int]]:
    distribution: dict[str, Counter[str]] = defaultdict(Counter)
    for example in examples:
        distribution[str(example.meta["question_id"])][str(example.meta["answer_id"])] += 1
    return {question_id: dict(counts) for question_id, counts in sorted(distribution.items())}


def run_quality_gates(
    splits: dict[str, list[Example]],
    framework: RiskFramework,
    settings: CorpusSettings,
) -> dict[str, Any]:
    """Evaluate every build-blocking gate and return a structured report."""
    all_examples = [example for name in SPLITS for example in splits[name]]
    checks: list[dict[str, Any]] = []

    def record(name: str, passed: bool, detail: Any) -> None:
        checks.append({"gate": name, "passed": bool(passed), "detail": detail})

    # Gate 1 — a Tier A input must not contain the source the label came from.
    leaked = [
        {"canonical_id": example.meta["canonical_id"], "question_id": example.meta["question_id"]}
        for example in all_examples
        if example.meta["tier"] == TIER_A
        and any(source.lower().startswith(NARA_SOURCE_PREFIX) for source in example.input_source_ids)
    ]
    record("tier_a_contains_no_nara_evidence", not leaked, {"violations": leaked[:20], "count": len(leaked)})

    # Gate 2 — every cited ref must exist in that example's own input.
    unresolved = [
        {
            "canonical_id": example.meta["canonical_id"],
            "question_id": example.meta["question_id"],
            "refs": sorted(set(example.target["evidence_refs"]) - set(example.referenced_refs)),
        }
        for example in all_examples
        if set(example.target["evidence_refs"]) - set(example.referenced_refs)
    ]
    record("citations_resolve_to_supplied_evidence", not unresolved, {"violations": unresolved[:20], "count": len(unresolved)})

    # Gate 3 — a format may not appear in more than one split.
    formats_by_split = {
        name: {str(example.meta["canonical_id"]) for example in splits[name]} for name in SPLITS
    }
    overlaps: dict[str, list[str]] = {}
    for left in SPLITS:
        for right in SPLITS:
            if left >= right:
                continue
            shared = sorted(formats_by_split[left] & formats_by_split[right])
            if shared:
                overlaps[f"{left}|{right}"] = shared[:20]
    record("no_format_in_two_splits", not overlaps, {"overlaps": overlaps})

    # Gate 4 — per-question test metrics need a denominator. Questions the
    # registry cannot evidence at all are reported separately: an unanswerable
    # question is a coverage gap for evidence_gaps.py, not a corpus defect.
    answerable = [example for example in all_examples if not example.meta.get("abstention")]
    answerable_questions = {str(example.meta["question_id"]) for example in answerable}
    test_counts = Counter(str(example.meta["question_id"]) for example in splits[SPLIT_TEST])
    corpus_questions = {str(example.meta["question_id"]) for example in all_examples}
    unbound = sorted({question.id for question in framework.questions} - corpus_questions)
    # A question carrying only Tier C abstentions has no label the registry can
    # produce. That is a coverage gap, not a thin sample, and it is reported
    # separately so the failure is diagnosable rather than just a zero.
    label_less = sorted(corpus_questions - answerable_questions)
    thin = {
        question_id: test_counts.get(question_id, 0)
        for question_id in sorted(answerable_questions)
        if test_counts.get(question_id, 0) < settings.min_test_examples_per_question
    }
    record(
        "every_bound_question_has_minimum_test_examples",
        not thin and not label_less,
        {
            "minimum": settings.min_test_examples_per_question,
            "below_minimum": thin,
            "questions_without_answerable_examples": label_less,
            "unbound_questions": unbound,
        },
    )

    # Gate 5 — a question whose answers are nearly all one value teaches the
    # prior, and a majority-class predictor would score as well as the model.
    # Computed over answerable examples only: Tier C is 100% abstention by
    # construction, so including it would flag every question as degenerate.
    distribution = _answer_distribution(answerable)
    degenerate = {}
    for question_id, counts in distribution.items():
        total = sum(counts.values())
        if not total:
            continue
        top_answer, top_count = max(counts.items(), key=lambda item: (item[1], item[0]))
        share = top_count / total
        if share > settings.max_answer_share:
            degenerate[question_id] = {"answer_id": top_answer, "share": round(share, 4), "total": total}
    record(
        "answer_distribution_not_degenerate",
        not degenerate,
        {"maximum_share": settings.max_answer_share, "degenerate": degenerate, "scope": "answerable_examples"},
    )

    # Gate 6 — too few abstention examples and the model answers from nothing;
    # too many and it abstains on answerable questions.
    total = len(all_examples)
    abstentions = sum(1 for example in all_examples if example.meta.get("abstention"))
    share = (abstentions / total) if total else 0.0
    low = settings.abstention_share - settings.abstention_tolerance
    high = settings.abstention_share + settings.abstention_tolerance
    record(
        "abstention_share_within_band",
        low <= share <= high,
        {"share": round(share, 4), "target": settings.abstention_share, "band": [round(low, 4), round(high, 4)],
         "abstention_examples": abstentions, "total_examples": total},
    )

    return {
        "passed": all(check["passed"] for check in checks),
        "checks": checks,
        "answer_distribution": distribution,
    }


def build_manifest(
    splits: dict[str, list[Example]],
    framework: RiskFramework,
    settings: CorpusSettings,
    construction: dict[str, Any],
    split_info: dict[str, Any],
) -> dict[str, Any]:
    all_examples = [example for name in SPLITS for example in splits[name]]
    by_tier = Counter(str(example.meta["tier"]) for example in all_examples)
    by_criterion = Counter(
        criterion for example in all_examples for criterion in example.meta.get("criterion", [])
    )
    source_ids = sorted({source for example in all_examples for source in example.input_source_ids})
    return {
        "corpus_version": settings.corpus_version,
        "framework": {
            "framework_id": framework.framework_id,
            "version": framework.version,
            "question_count": len(framework.questions),
        },
        "settings": {
            "tiers": list(settings.tiers),
            "abstention_share": settings.abstention_share,
            "abstention_tolerance": settings.abstention_tolerance,
            "split_seed": settings.split_seed,
            "test_share": settings.test_share,
            "val_share": settings.val_share,
            "max_evidence_items": settings.max_evidence_items,
            "institution_id": settings.institution_id,
            "max_formats": settings.max_formats,
        },
        "counts": {
            "total": len(all_examples),
            "by_split": {name: len(splits[name]) for name in SPLITS},
            "by_tier": dict(sorted(by_tier.items())),
            "by_question": dict(sorted(Counter(str(e.meta["question_id"]) for e in all_examples).items())),
            "by_criterion": dict(sorted(by_criterion.items())),
            "by_answer": _answer_distribution(all_examples),
            "by_answer_answerable": _answer_distribution(
                [example for example in all_examples if not example.meta.get("abstention")]
            ),
            "abstention_examples": sum(1 for example in all_examples if example.meta.get("abstention")),
        },
        "label_source": LABEL_SOURCE,
        "evidence_view": "raw_source_only",
        "input_source_ids": source_ids,
        "construction": construction,
        "split": split_info,
    }


def write_corpus(out_dir: Path, splits: dict[str, list[Example]]) -> dict[str, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}
    for name in SPLITS:
        path = out_dir / f"{name}.jsonl"
        with path.open("w", encoding="utf-8") as handle:
            for example in splits[name]:
                handle.write(json.dumps(example.to_record(), sort_keys=True) + "\n")
        written[name] = str(path)
    return written


def build_training_corpus(
    reader: RegistryReader,
    framework: RiskFramework,
    settings: CorpusSettings,
    out_root: Path,
) -> dict[str, Any]:
    """Build, gate, and write a versioned training corpus.

    Returns a summary including the gate report. The caller decides what a gate
    failure means; the corpus is written either way so a failed build can be
    inspected rather than only described.
    """
    examples, construction = generate_examples(reader, framework, settings)

    # Split on the answerable examples first, then size Tier C against what
    # actually survives that split. Sizing it against the pre-split count leaves
    # the corpus short of its abstention target once held-out rows are dropped.
    membership = split_formats([str(item.meta["canonical_id"]) for item in examples], settings)
    answerable_splits, _ = assign_splits(examples, settings, membership=membership)
    surviving = sum(len(rows) for rows in answerable_splits.values())

    target_abstentions = 0
    if TIER_C in settings.tiers and settings.abstention_share > 0:
        target_abstentions = int(round(settings.abstention_share * surviving / (1 - settings.abstention_share)))
    abstentions = generate_abstention_examples(
        reader,
        framework,
        settings,
        target_abstentions,
        exclude_formats=membership[SPLIT_TEST] | membership[SPLIT_VAL],
    )
    construction["answerable_after_split"] = surviving
    construction["abstention_target"] = target_abstentions
    construction["abstention_built"] = len(abstentions)

    splits, split_info = assign_splits(examples + abstentions, settings, membership=membership)
    gates = run_quality_gates(splits, framework, settings)
    manifest = build_manifest(splits, framework, settings, construction, split_info)

    out_dir = out_root / settings.corpus_version
    files = write_corpus(out_dir, splits)
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    (out_dir / "leakage_report.json").write_text(json.dumps(gates, indent=2, sort_keys=True), encoding="utf-8")

    return {
        "status": "ok" if gates["passed"] else "quality_gates_failed",
        "corpus_version": settings.corpus_version,
        "output_dir": str(out_dir),
        "files": {
            **files,
            "manifest": str(out_dir / "manifest.json"),
            "leakage_report": str(out_dir / "leakage_report.json"),
        },
        "counts": manifest["counts"],
        "construction": construction,
        "split": split_info,
        "quality_gates": {
            "passed": gates["passed"],
            "failed": [check["gate"] for check in gates["checks"] if not check["passed"]],
            "checks": gates["checks"],
        },
    }
